import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Home, Settings, Users, Wallet } from "lucide-react";

const TODAY = new Date().toISOString().slice(0,10);
const seed = () => ({
  settings:{shopName:"NO RAZORS",barberName:"ZEU",cancellationWindowHours:2,cancellationFeePercent:20,taxEstimatePercent:25},
  services:[{id:"cut",name:"Signature Cut",duration:45,price:45},{id:"beard",name:"Cut + Beard",duration:60,price:60},{id:"line",name:"Line Up",duration:25,price:25}],
  clients:[{id:"c1",name:"Malik Carter",phone:"210-555-0184",preferredCut:"Low taper",notes:"Keep the line natural."},{id:"c2",name:"Andre Lewis",phone:"210-555-0137",preferredCut:"Cut + beard",notes:"Medium fade."}],
  appointments:[{id:"a1",clientId:"c1",clientName:"Malik Carter",serviceId:"cut",serviceName:"Signature Cut",date:TODAY,time:"10:00",duration:45,price:45,status:"confirmed",paymentStatus:"deposit-paid"},{id:"a2",clientId:"c2",clientName:"Andre Lewis",serviceId:"beard",serviceName:"Cut + Beard",date:TODAY,time:"13:30",duration:60,price:60,status:"confirmed",paymentStatus:"unpaid"}],payments:[]
});
const money = n => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);

function Splash(){return <div className="splash"><div className="noise"/><div className="vertical">FLOSS</div><div className="splash-copy"><span>NO RAZORS</span><h1>BARBER<br/>OS</h1><p>ZEU — MADE BY ZEUS</p></div></div>}
function Head({data}){return <header><div><small>FLOSS SYSTEM / 01</small><h1>{data.settings.shopName}</h1></div><b>LIVE</b></header>}
function Card({children,className=""}){return <div className={`card ${className}`}>{children}</div>}

function Dashboard({data,stats,act}){const next=stats.today.find(a=>a.status==="confirmed");return <section><div className="hero"><small>TODAY / GROSS</small><strong>{money(stats.todayRevenue)}</strong><p>{stats.today.length} appointments on deck</p></div><div className="metrics"><Card><small>ALL CHAIRS</small><b>{stats.active.length}</b></Card><Card><small>CANCEL FEES</small><b>{money(stats.fees)}</b></Card></div><Title a="NEXT CHAIR" b={data.settings.barberName}/>{next?<Appointment a={next} act={act} featured/>:<Card><h3>BOARD CLEAR</h3><p>No confirmed appointments today.</p></Card>}<Title a="TODAY'S SCHEDULE"/><div className="stack">{stats.today.map(a=><Appointment key={a.id} a={a} act={act}/>)}</div></section>}
function Title({a,b}){return <div className="title"><h2>{a}</h2><span>{b}</span></div>}
function Appointment({a,act,featured}) {return <Card className={featured?"featured":""}><div className="row"><div><small>{a.date} / {a.time}</small><h3>{a.clientName}</h3><p>{a.serviceName} · {money(a.price)} · {a.status}</p>{a.cancellationFeeApplied&&<em>{money(a.cancellationFeeAmount)} fee applied</em>}</div>{a.status==="confirmed"&&<div className="actions"><button onClick={()=>act("done",a.id)}>DONE</button><button onClick={()=>act("cancel",a.id)}>CANCEL</button></div>}</div></Card>}

function Bookings({data,add,act}){const [f,setF]=useState({clientId:data.clients[0]?.id||"",serviceId:data.services[0]?.id||"",date:TODAY,time:"10:00",depositPaid:10});return <section><Title a="BOOK CHAIR" b="UNDER 30 SEC"/><form onSubmit={e=>{e.preventDefault();add(f)}}><label>CLIENT<select value={f.clientId} onChange={e=>setF({...f,clientId:e.target.value})}>{data.clients.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>SERVICE<select value={f.serviceId} onChange={e=>setF({...f,serviceId:e.target.value})}>{data.services.map(x=><option value={x.id} key={x.id}>{x.name} — {money(x.price)}</option>)}</select></label><div className="fields"><label>DATE<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>TIME<input type="time" value={f.time} onChange={e=>setF({...f,time:e.target.value})}/></label></div><label>DEPOSIT<input type="number" value={f.depositPaid} onChange={e=>setF({...f,depositPaid:+e.target.value})}/></label><button className="primary">CONFIRM BOOKING</button></form><Title a="ALL BOOKINGS"/><div className="stack">{[...data.appointments].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(a=><Appointment key={a.id} a={a} act={act}/>)}</div></section>}

function Clients({data,add}){const [q,setQ]=useState("");const [f,setF]=useState({name:"",phone:"",preferredCut:"",notes:""});return <section><Title a="CLIENTS" b={`${data.clients.length} SAVED`}/><input className="search" placeholder="SEARCH CLIENTS" value={q} onChange={e=>setQ(e.target.value)}/><form onSubmit={e=>{e.preventDefault();if(f.name.trim()){add(f);setF({name:"",phone:"",preferredCut:"",notes:""})}}}>{[["name","NAME"],["phone","PHONE"],["preferredCut","PREFERRED CUT"],["notes","NOTES"]].map(([k,l])=><label key={k}>{l}<input value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<button className="primary">ADD CLIENT</button></form><div className="stack">{data.clients.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())).map(c=><Card key={c.id}><small>{c.phone}</small><h3>{c.name}</h3><p>{c.preferredCut}</p><p>{c.notes}</p></Card>)}</div></section>}

function Money({data,stats}){const gross=stats.allRevenue,tax=Math.round(gross*data.settings.taxEstimatePercent/100);const rows=Object.values(stats.active.reduce((m,a)=>{m[a.serviceName]??={name:a.serviceName,count:0,total:0};m[a.serviceName].count++;m[a.serviceName].total+=+a.price;return m},{}));return <section><div className="hero invert"><small>MONEY BOARD / GROSS</small><strong>{money(gross)}</strong><p>visible revenue</p></div><div className="metrics"><Card><small>TAX SET ASIDE</small><b>{money(tax)}</b></Card><Card><small>NET ESTIMATE</small><b>{money(gross-tax)}</b></Card></div><Title a="SERVICE HEAT"/><div className="stack">{rows.map(r=><Card key={r.name}><div className="row"><div><h3>{r.name}</h3><p>{r.count} bookings</p></div><h2>{money(r.total)}</h2></div></Card>)}</div></section>}

function Setup({data,save,reset}){const [f,setF]=useState(data.settings);return <section><Title a="SETTINGS" b="BARBER RULES"/><form onSubmit={e=>{e.preventDefault();save(f)}}>{[["shopName","SHOP NAME"],["barberName","BARBER NAME"],["cancellationWindowHours","CANCEL WINDOW / HOURS"],["cancellationFeePercent","CANCEL FEE / %"],["taxEstimatePercent","TAX ESTIMATE / %"]].map(([k,l])=><label key={k}>{l}<input value={f[k]} type={k.includes("Percent")||k.includes("Hours")?"number":"text"} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<button className="primary">SAVE SETTINGS</button></form><button className="reset" onClick={reset}>RESET DEMO DATA</button><Card><small>POLICY / ACTIVE</small><p>Cancel at least {data.settings.cancellationWindowHours} hours before the appointment or a {data.settings.cancellationFeePercent}% fee applies.</p></Card></section>}

export default function App(){const [show,setShow]=useState(true);const [tab,setTab]=useState("home");const [data,setData]=useState(()=>{try{return JSON.parse(localStorage.getItem("floss-data"))||seed()}catch{return seed()}});useEffect(()=>{localStorage.setItem("floss-data",JSON.stringify(data))},[data]);useEffect(()=>{const t=setTimeout(()=>setShow(false),1400);return()=>clearTimeout(t)},[]);const stats=useMemo(()=>{const active=data.appointments.filter(a=>a.status!=="cancelled"),today=data.appointments.filter(a=>a.date===TODAY&&a.status!=="cancelled"),fees=data.payments.filter(p=>p.type==="cancellation-fee").reduce((s,p)=>s+Number(p.amount||0),0);return{active,today,fees,todayRevenue:today.reduce((s,a)=>s+Number(a.price||0),0),allRevenue:active.reduce((s,a)=>s+Number(a.price||0),0)+fees}},[data]);function act(type,id){setData(d=>{const a=d.appointments.find(x=>x.id===id);if(!a)return d;if(type==="done")return{...d,appointments:d.appointments.map(x=>x.id===id?{...x,status:"completed",paymentStatus:"paid"}:x)};const hours=(new Date(`${a.date}T${a.time}`)-new Date())/36e5,applies=hours<+d.settings.cancellationWindowHours,amount=applies?Math.round(a.price*+d.settings.cancellationFeePercent/100):0;return{...d,appointments:d.appointments.map(x=>x.id===id?{...x,status:"cancelled",cancellationFeeApplied:applies,cancellationFeeAmount:amount}:x),payments:applies?[...d.payments,{id:crypto.randomUUID(),type:"cancellation-fee",amount}]:d.payments}})}function addBooking(f){setData(d=>{const c=d.clients.find(x=>x.id===f.clientId),s=d.services.find(x=>x.id===f.serviceId);if(!c||!s)return d;return{...d,appointments:[...d.appointments,{id:crypto.randomUUID(),clientId:c.id,clientName:c.name,serviceId:s.id,serviceName:s.name,date:f.date,time:f.time,duration:s.duration,price:s.price,depositPaid:+f.depositPaid||0,status:"confirmed",paymentStatus:f.depositPaid>0?"deposit-paid":"unpaid"}]}})}function addClient(f){setData(d=>({...d,clients:[...d.clients,{...f,id:crypto.randomUUID(),lifetimeSpend:0}]}))}const pages={home:<Dashboard data={data} stats={stats} act={act}/>,bookings:<Bookings data={data} add={addBooking} act={act}/>,clients:<Clients data={data} add={addClient}/>,money:<Money data={data} stats={stats}/>,settings:<Setup data={data} save={s=>setData(d=>({...d,settings:{...d.settings,...s}}))} reset={()=>{setData(seed());setTab("home")}}/>};if(show)return <Splash/>;return <div className="shell"><Head data={data}/><main>{pages[tab]}</main><nav>{[["home",Home,"HOME"],["bookings",CalendarDays,"BOOK"],["clients",Users,"CLIENTS"],["money",Wallet,"MONEY"],["settings",Settings,"SET"]].map(([id,I,l])=><button key={id} className={tab===id?"on":""} onClick={()=>setTab(id)}><I size={18}/><span>{l}</span></button>)}</nav></div>}
